In [6]:
import numpy
import tflearn
import tensorflow as tf
import random
import json

from data import DataProcessing

In [7]:
with open('intents.json') as file:
    data = json.load(file)

objt_1 = DataProcessing(data) #Constructor
objt_1.start_process() # Generate data

print(objt_1.training[0])
print(objt_1.output)

step 1
[] []
step 2
step 3
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0]
[[0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 1 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]]


In [9]:
tf.compat.v1.reset_default_graph()

net = tflearn.input_data(shape=[None, len(objt_1.training[0])])
net = tflearn.fully_connected(net, 8)
net = tflearn.fully_connected(net, 8)
net = tflearn.fully_connected(net, len(objt_1.output[0]), activation="softmax")
net = tflearn.regression(net)

model = tflearn.DNN(net)

In [11]:
model.fit(objt_1.training, objt_1.output, n_epoch=1000, batch_size=8, show_metric=True)
model.save("model.tflearn")

Training Step: 3999  | total loss: 0.00507 | time: 0.008s
| Adam | epoch: 1000 | loss: 0.00507 - acc: 1.0000 -- iter: 24/26
Training Step: 4000  | total loss: 0.00566 | time: 0.011s
| Adam | epoch: 1000 | loss: 0.00566 - acc: 1.0000 -- iter: 26/26
--
INFO:tensorflow:C:\Users\alahp\Desktop\APcodes\projects\ML\chatbot-2\model.tflearn is not in all_model_checkpoint_paths. Manually adding it.
